name: s3 Deploy
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ITEMS_TO_INVALIDATE: ${{ secrets.AWS_ITEMS_TO_INVALIDATE }}
      AWS_CLOUDFRONT_DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
      SOURCE_DIR: 'build'      # optional: defaults to entire repository
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
    - uses: brennanmcdonald/cloudfront-create-invalidation@master

